name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # match your runtime.txt if you use one

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # optional: add linters/typing
          pip install pytest pytest-cov flake8 mypy

      - name: Lint (flake8)
        run: flake8 .

      - name: Type check (mypy)
        run: mypy . || true  # set to fail build if you want strict typing

      - name: Run tests
        run: pytest -q
